# Generated by Django 4.1.7 on 2023-04-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0002_delete_userprofile"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="trips",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="trips",
            field=models.ManyToManyField(
                blank=True, related_name="passengers", to="flights.flight"
            ),
        ),
    ]
