# Generated by Django 4.1.7 on 2023-05-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        ("users", "0003_userprofile_credit"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="cart",
            field=models.ManyToManyField(blank=True, to="products.product"),
        ),
    ]
