# Generated by Django 4.1.7 on 2023-04-12 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="userProfile",
        ),
    ]
