# Generated by Django 4.1.7 on 2023-05-05 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0002_delete_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="cost",
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="flight",
            name="destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arrival",
                to="flights.airport",
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="origin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departure",
                to="flights.airport",
            ),
        ),
    ]
